url: https://dannyphillips.me
baseurl: 

# Site settings
title: Danny Phillips
email: danny.phillips8l@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3399ff
  secondary: 3333ff  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dphil4life
  - title: google-plus
    url:  https://plus.google.com/u/1/+DannyPhillips8/
  - title: linkedin
    url: https://www.linkedin.com/in/dannyphillips1
  - title: instagram 
    url: https://instagram.com/dannyphillips8/
  - title: bitbucket
    url: https://bitbucket.org/dannyphillips/ 
  - title: github
    url: http://github.com/dannyphillips

# Postal address (add as many lines as necessary)
address:
  - line: 1217 Cypress Point Ln
  - line: Ventura, CA 93003

# Build settings
markdown: kramdown
permalink: pretty