# Site settings
title: Danny Phillips
description: Danny Phillips's Personal Site
favicon: /iCard-Resume/assets/img/avatar.JPG
url: https://ddbullfrog.github.io/iCard-Resume
rss_url: /iCard-Resume/pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Danny Phillips
  title: Software Engineer
  address: Santa Barbara, California
  email: danny.phillips8@gmail.com
  link: http://dannyphillips.me
  weibo:
  github: dannyphillips
  linkedin: dannyphillips1
  twitter: dphil4life
  gavatar: /dannyphillips.github.io/assets/img/avatar.JPG
  workHistory:
    - work1:
      company: Procore Technologies
      location: Carpinteria, California
      title: Software Engineer
      started: September 2014
      duration: (September 2014 - Present)
      description: I am a Front-End Developer for a Ruby on Rails application. I work primarily in javascript creating intuitive user-interfaces with React components.
    - work2:
      company: Kollabra Consulting
      location: Goleta, California
      title: Mechanical Engineer II
      started: June 2013
      duration: (June 2013 - September 2014)
      description: I did cool things.
    - work3:
      company: UCSB ResNet
      location: Santa Barbara, California
      title: Senior Network Technician
      started: April 2010
      duration: (April 2010 - June 2013)
      description: I fixed all the things
    - work4:
      company: Westco Intl
      location: Santa Barbara, California
      title: Mechanical Engineer I 
      started: March 2013
      duration: (March 2013 - June 2013)
      description: I fixed all the things
  educationHistory:
    - education1:
      organization: Northeastern University
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  Other :
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: AngularJS
      percentage: 80%
    - skill5:
      name: Java/Java EE
      percentage: 90%
