url: https://dannyphillips.me
baseurl: /home/

# Site settings
title: Danny Phillips
email: danny.phillips8l@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3399ff
  secondary: 3333ff  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dphil4life
  - title: google-plus
    url:  http://plus.google.com/dannyphillips8
  - title: linkedin
    url: http://linkedin.com/dannyphillips1
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/dannyphillips

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty